### PR TITLE
Add strict password policy

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | We need to apply a some JS in order to show password policy tips
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Go on register as a customer, type your password and have fun!
| Possible impacts? | Register as a customer

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @NeOMakinG ,

I have tested multiple cases : 
use of only letters, mix of upper and lower cases
only digits
mix of letters and digits
special characters
mix of letters, digits and special characters
use of spaces
use of real words/use of series of letters
repetition of a word
use of a sequence like "abc" or "123"
use of dates
use of @ to replace a, use of 3 to replace E

I have found an issue :
- When I type a password with `^` character, it won't type in the field. But if I click on SHOW the password, I can type the character `^` it with no issue.
Same behavior with character ` and  ¨ 

https://user-images.githubusercontent.com/16019289/173768365-738cb17c-32a7-481c-9421-3e741a4f98af.mov

Could you check ?
Thanks!

**Comment by sLorenzini** [comment]
> Hello @NeOMakinG ,
> 
> I have tested multiple cases : use of only letters, mix of upper and lower cases only digits mix of letters and digits special characters mix of letters, digits and special characters use of spaces use of real words/use of series of letters repetition of a word use of a sequence like "abc" or "123" use of dates use of @ to replace a, use of 3 to replace E
> 
> I have found an issue :
> 
>     * When I type a password with `^` character, it won't type in the field. But if I click on SHOW the password, I can type the character `^` it with no issue.
>       Same behavior with character ` and  ¨
> 
> 
> Screen.Recording.2022-06-15.at.09.26.35.mov
> 
> Could you check ? Thanks!

hello @NeOMakinG,

I've tested the same cases on hide/show password as @florine2623. All good
But I reproduce the same issue as @florine2623.
My screenrecord:

https://user-images.githubusercontent.com/2854834/177329942-5ac64eeb-93c2-459c-9bf1-ead695bcb0f1.mp4

Here's are the characters to test for the issue: ¨, ^, `

Could you check please 🙏?

Thanks

**Comment by NeOMakinG** [comment]
@sLorenzini @florine2623 https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password

This is a normal behavior, test on a regular password input and you'll notice it, I guess we don't have the power to do anything to this, you can also test on the demo of prestashop, it will do the same thing!

**Review by florine2623 — APPROVED** [review]
Hello @NeOMakinG ,

Ok, noted, thanks for the details ^^

Tested again on develop and 8.0.x, on connection page and order as a guest page.

Looking good to me.
It is QA ✅

**Comment by NeOMakinG** [comment]
Thanks @florine2623 and @sLorenzini for your time and everyone for the review

**Pull request merged**
