### PR TITLE
Added module `psgdpr` in Core

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Added module `psgdpr` in Core
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Relative to PrestaShop/Prestashop#27962
| How to test?      | Install the module psgdpr, install Prestashop, and the icon should be present in the customer backoffice.

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Ok for this fix related to the classic theme

But I'm surprised the module cannot hook itself on install 🤔. Is it because the installation of modules during the Shop install process is a bit different? And requires this config to work correctly?

**Comment by Progi1984** [comment]
@jolelievre It's normal : when a hook is defined in theme.yml, all modules connected to this hooks are unhooked. It's better to have all modules correctly defined.

Code : https://github.com/PrestaShop/PrestaShop/blob/ac732eea379391e621c02d3636026f65edeef828/src/Core/Module/HookRepository.php#L136

**Review by florine2623 — APPROVED** [review]
Hello @Progi1984 ,

Thanks for the update, this solves the issue mentioned in https://github.com/PrestaShop/PrestaShop/pull/27962#pullrequestreview-934748557

It is QA ✅

**Comment by Progi1984** [comment]
Thanls @florine2623

**Pull request merged**
