### PR TITLE
feat: Adds mobile and phone preview for future updates

### PR DESCRIPTION
**Pull request by amaury-hanser**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Added 2 previews, one for mobile and one for tablet. <br>In the **Theme** page in the back-office, only the regular preview is used now, but we intend to add a feature to show a preview for mobile. See below picture.
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no

---

## More informations
We are working on a rework of the different pages of the "Design" entry in the back-office.  
The rework is done by a module, but some features might be pushed to the core later.

One of the feature is to show a preview of the theme for mobile and desktop as seen on this picture:

image

As it's a feature that we would like to see on the core, we think that the `classic _theme` should be the first to have this feature available.

Would that be OK?

### CODE REVIEW

**Comment by Hlavtox** [comment]
I would keep it open for now and merge when the PR on core is merged. ;-)

I love the design of theme page you included!

**Comment by amaury-hanser** [comment]
Scott did a good job on the design, I agree.  

The feature will be developed in a module first as PrestaShop 8 is freezed.  
The module (developed by PrestaShop) should be live on October.

**Comment by NeOMakinG** [comment]
> I would keep it open for now and merge when the PR on core is merged. ;-)
> 
> I love the design of theme page you included!

As this will come out as a module first, it can be released at any time, so I guess we shouldn't wait to merge it

**Review by NeOMakinG — APPROVED** [review]
@PrestaShop/prestashop-maintainers I would like your advice on this

🍬 for me, even if the core won't use it asap

**Review by kpodemski — APPROVED** [review]

**Review by matks — APPROVED** [review]
@NeOMakinG I agree too

**Comment by matks** [comment]
3 maintainers approved :) I guess we can merge

**Comment by matks** [comment]
Thank you @amaury-hanser

**Pull request merged**
