### PR TITLE
Add `data-role` attributes for links in `my-account-links.tpl`

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add `data-role` attributes for links in `my-account-links.tpl`
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | Checkout the PR PrestaShop/PrestaShop#29785 with this PR in the theme and run the command for test : `HEADLESS=false TEST_PATH="functional/FO/03*/01*/01*" URL_FO="https://domain.tld/" npm run test:specific`
| Possible impacts? | N/A

### CODE REVIEW

**Comment by SharakPL** [comment]
Any reason for this?

**Comment by Progi1984** [comment]
@SharakPL Yes of course. We need it for automated tests.

**Comment by matks** [comment]
> Any reason for this?

As mentioned by @Progi1984, adding IDs to html items allow to target them in automated tests. Also I guess the more IDs we have the better it is to allow people to customize accurately CSS if they choose to use Classic as a base, or to allow JavaScript improvements from third party modules to target items.

**Review by matks — APPROVED** [review]

**Comment by Hlavtox** [comment]
@matks Classes should be used for styling, not IDs.

Is there a way to add specific selectors for tests and strip them on build?

**Comment by SharakPL** [comment]
> > Any reason for this?
> 
> As mentioned by @Progi1984, adding IDs to html items allow to target them in automated tests. Also I guess the more IDs we have the better it is to allow people to customize accurately CSS if they choose to use Classic as a base, or to allow JavaScript improvements from third party modules to target items.

I get that, but it seems pointless to add something to the templates just to be used in tests. I'd say the tests need changes, not the template.

**Comment by Progi1984** [comment]
Fixed : I change identifiers by `data-role` attributes

**Comment by Hlavtox** [comment]
That looks good!

**Review by Hlavtox — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by SharakPL — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @Progi1984 !

No need QA on this one, thanks :)

**Pull request merged**
