### PR TITLE
Fixes contact page responsive

### LINKED ISSUE #33415: [Responsive] Contact page is badly displayed
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

From `767px` to `567px`, the contact page is badly displayed, cause: 

- `col-sm-4` should be `col-md-4`
- `col-md-3` should be `col-lg-3`

image

### Expected behavior

image

### Steps to reproduce

1. FO>Contact us
2. Use responsive mode, click F12
3. Shrink the window to width 650px
4. See error > bad display

### PrestaShop version(s) where the bug happened

1.7.8.8 & 8.0.4 & 8.1.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by iamtiagogalvao**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Changed col classes that were causing a responsive issue on 767px to 567px screen sizes. `col-sm-4` was changed to` col-md-4 `and `col-md-3` was changed to `col-lg-3`.
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes 
| Sponsor company   | Not applicable
| How to test?      | See ticket. Navigate to Contact us page  -> Use responsive mode, click F12 -> Shrink the window to width 650px -> See fix > columns now display correctly in tablet.

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Thank you @Slaveworx 😉 sounds good

Can I suggest to change the target branch to `2.1.x`? This will allow users of PS 8.1.x to benefit from this change

If we merge this PR in `develop` it will only be usable for 9.0.0 users

**Review by matthieu-rolland — APPROVED** [review]
looks good to me, but review from some frontend aficionado would be nice too

**Comment by Hlavtox** [comment]
@Slaveworx Hey, good change. Please, rebase it onto 2.1.x, these merge prs don't work very well. Thank you! :-)

**Comment by iamtiagogalvao** [comment]
> @Slaveworx Hey, good change. Please, rebase it onto 2.1.x, these merge prs don't work very well. Thank you! :-)

I have completed the rebase onto 2.1.x.

**Comment by matks** [comment]
@Slaveworx if you just change the target branch, you also get a lot of unwanted commits

You need to either use `git rebase` or `git cherry-pick`

I recommend cherry pick

**Comment by iamtiagogalvao** [comment]
> @Slaveworx if you just change the target branch, you also get a lot of unwanted commits
> 
> You need to either use `git rebase` or `git cherry-pick`
> 
> I recommend cherry pick

Closed this PR and opened a new one here: #123.

**Pull request closed without merging**
