### PR TITLE
quantity input correction

### LINKED ISSUE #30911: [Classic theme] Quantity form unstable structure
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Feedback from @MhiriFaten: https://github.com/PrestaShop/ps_linklist/pull/155#pullrequestreview-1250294891

image

When product columns are enabled and/or simply viewing product page on smaller screens, squeezed main content cause quantity form to lose structure.

### Expected behavior

Quantity form should look the same under any circumstances and buttons next to it should wrap into new line if needed

### Steps to reproduce

1. Follow the steps from #30802
2. Optionaly use smaller screen size
3. Check the structure of quantity form

### PrestaShop version(s) where the bug happened

1.7, 8.x

### PHP version(s) where the bug happened

7.x, 8.x

### If your bug is related to a module, specify its name and its version

classic-theme

### PR DESCRIPTION
**Pull request by JBLach**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | quantity input correction
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes [#30911](https://github.com/PrestaShop/PrestaShop/issues/30911)
| Sponsor company   | Your company or customer's name goes here (if applicable).
| How to test?      | All the details are on the issue.

## Before
image

## After
image

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
Default `flex-wrap` value is `nowrap`, no need to specify it further. ✅

**Comment by SharakPL** [comment]
Issue is not just about input group. The main cause  of that is whole block with add to cart and wishlist is not allowed to wrap. Can you add this fix to this PR?

**Review by SharakPL — CHANGES_REQUESTED** [review]
Issue is not just about input group. The main cause  of that is whole block with add to cart and wishlist is not allowed to wrap. Can you add this fix to this PR?

**Comment by JBLach** [comment]
> Issue is not just about input group. The main cause of that is whole block with add to cart and wishlist is not allowed to wrap. Can you add this fix to this PR?

Hi @SharakPL 
Would you have an idea what to do with the wishlist icon, when we set flex-wrap: wrap; sometimes it may be a case that this icon is alone in the line, and it has margin-left, which is hard to override

image
image

**Comment by SharakPL** [comment]
IMO this button should be on the product image, just like it is on products list or somewhere near the product title:
obraz

In area with quantity input only order related actions should be allowed.
But changes like that would have to be made in blockwishlist module (move to different hook) or in Hummingbird theme. No point to change it here in classic. If anything I would simply decrease margin a little:
```css
.wishlist-button-product {
  margin-left: 0.5rem !important;
}
```
obraz

**Review by SharakPL — APPROVED** [review]

**Comment by AureRita** [comment]
Hi @JBLach 

Thank you for your PR ! I tried it and it correct the issue as we can see : 

image

but we also see that the wishlist button is on a different line. If we have a short add to cart button. we have this button on an other line than the quantity, as we can see : 

image

@PrestaShop/product-team is it what we want ? 

FYI : I do it with a three column on the product page

If it's ok for the PM, I will put it in QA approved :heavy_check_mark: 

Thank you !

**Comment by Hlavtox** [comment]
This should go to 2.0.x, 2.1.x and develop.

**Review by AureRita — APPROVED** [review]
Seen with @MatShir 

this PR is QA validated :heavy_check_mark:

**Comment by nicosomb** [comment]
Thank you @JBLach @AureRita !

**Pull request merged**
