### PR TITLE
Update theme version and require PS 8 minimum

### LINKED ISSUE #28387: FO > Page Product, Exceptions when you use latest classic-theme changes on 1.7.8.x
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I Go to the FO, Click on See all product or a category of product, I've this exception : 
image

Just after an installation of a classic-theme to test it, it doesn't happen on develop

### Expected behavior

I want to see the product with the faceted search on the left

### Steps to reproduce

1. Install a classic-theme like this one : https://github.com/PrestaShop/classic-theme/pull/26 : so you use **the latest classic-theme changes**
2. Install your shop
3. Go on FO 
4. Clic on "All products" 
5. See the exception

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

https://github.com/PrestaShop/classic-theme/pull/26

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Updated the theme version to 2 to distinguish it from the version running in 1.7. Added minimum compatibility to PS 8. I also updated the theme's author information.
| Type?             | new feature
| BC breaks?        | yes - compatibility updated
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/28387
| How to test?      | You can't install the theme on PS < 8
| Possible impacts? | This should only impact the theme's installation

### CODE REVIEW

**Review by matks — APPROVED** [review]
OK for me this will make clear to users that this classic-theme version is 2.0.0 (= contains BC breaks) and cannot be used with PrestaShop < 8

wdyt @NeOMakinG @Hlavtox

**Review by NeOMakinG — APPROVED** [review]
Agree, but only because of one BC added, the password policy

**Comment by PrestaEdit** [comment]
I hope you will have at least two branches : 1.7.x and 8.x, in order to continue the improvements onto the theme on 1.7 versions later, :)

**Comment by eternoendless** [comment]
@PrestaEdit any improvement for the 1.7 version will be done in the 1.7.8.x branch, according to our branch support policy (see https://devdocs.prestashop.com/8/contribute/contribution-guidelines/supported-branches/)

**Comment by PrestaEdit** [comment]
But this branch is not exists yet, on the classic-theme repo. Isn't it ?
This doc talk more about the main repo.

**Comment by kpodemski** [comment]
@PrestaEdit 

`classic-theme` repo is for v8+
`classic` from `1.7.8.x` is for 1.7

there will be no place for improvements on 1.7, only bugfixes

**Comment by PrestaEdit** [comment]
Thanks to @Progi1984 to make me this understable ; doesn't have in mind that the repo was moved only for 8.x branch, I was thinking it was made on a upper side.

**Review by PrestaEdit — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by sLorenzini — COMMENTED** [review]
hi @eternoendless,

Thank you for this PR.
Tested on 1.7.8.x/develop/8.0.x branches, PHP 7.3

On develop and 8.0.x, classic theme is well displayed without any errors and with the last version (2.0.0) ✅: 

Capture d’écran 2022-07-25 à 16 33 47
Capture d’écran 2022-07-25 à 16 25 28

On 1.7.8.x version, I've installed classic with this PR (version 2.0.0) and by keeping the current version 1.0.0. I couldn't install it but I have a successful message instead of an error in BO :

https://user-images.githubusercontent.com/2854834/180803333-bc53919a-f12e-4d08-8c46-5868797bf0e5.mp4




It is the good behavior? Could you please check 🙏?

Thanks

**Comment by eternoendless** [comment]
@sLorenzini I don't know why you get that weird behavior but it's likely a problem with the core itself. Did you rename one of the two themes?

**Comment by sLorenzini** [comment]
> @sLorenzini I don't know why you get that weird behavior but it's likely a problem with the core itself. Did you rename one of the two themes?

hello @eternoendless,

No I didn't rename any theme.
Just install your PR with the "new" theme by:
- keeping the current theme to see the difference
- replacing the current theme by the theme with this PR

In the second case, in the FO, the error is still displayed.
In all cases, it can be installed in PrestaShop with a successful message in the BO.

Let me know if I can test it again or do something more to test this PR.

Thanks

**Comment by NeOMakinG** [comment]
I guess this PR isn't blocked as it's a core issue, we could probably merge it :)

**Comment by eternoendless** [comment]
To me the problem is in the core and unrelated to this change, which to the best of my knowledge follows the guidelines.

The way I see it:
- If you have theme A installed and you try to install a newer version of theme A, you shouldn't have the theme installed twice; the previous theme should be updated
- A theme that is not compatible with the current core version should be rejected during the installation.

How about we note the bug, and merge this PR?

**Comment by MatShir** [comment]
LGTM, here the [issue](https://github.com/PrestaShop/PrestaShop/issues/29192) :) 
Let's merge it and release the theme !

**Review by sLorenzini — APPROVED** [review]
hello @eternoendless,

I've made new several tests on 1.7.8.6 and 8.0.0 version of PrestaShop with the new theme 2.0.0 version.
Here's my test:

- 1.7.8.6 version:
If I want to add the new classic zip with the current already installed, I've got this logical error

1786-add-template-with-other-classic

- 8.0.0 version:

1. If I add this template with the PR with command lines, the theme is correctly installed and there is no error on the FO

80x-new-theme-installed-command-lines
80x-FO-template-200

2. If I want to add it, with the current template installed (1.0.0), I've got this logical error

80x-add-zip-with-current-one

It's QA approved ✅ 

Thanks

**Comment by NeOMakinG** [comment]
Thanks @sLorenzini @eternoendless

**Pull request merged**
