### PR TITLE
Fix content width of registration form

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Changing the controller of registration did change the content width, we need to adjust it
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/pull/27755.
| How to test?      | Should be tested with https://github.com/PrestaShop/PrestaShop/pull/27755 , It fixes the width of the registration form with the new controller
| Possible impacts? | FO registration form

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by sLorenzini** [comment]
Hi @NeOMakinG,

Thank you for yout PR, I tested It and I see some little details that appear with this PR:

You have a little space after the radio button on the gender, as you can see:

- with this PR:

withpr

- with the branch dev without PR:

withoutpr


The content width of registration form is good

Thanks

**Comment by matks** [comment]
ping @NeOMakinG

**Comment by NeOMakinG** [comment]
> Hi @NeOMakinG,
> 
> Thank you for yout PR, I tested It and I see some little details that appear with this PR:
> 
> You have a little space after the radio button on the gender, as you can see:
> 
> * with this PR:
> 
> withpr
> 
> * with the branch dev without PR:
> 
> withoutpr
> 
> The content width of registration form is good
> 
> Thanks

Honestly, it's really nitpicking, classic doesn't have a real current state about such a detail, I wouldn't mind

I'll take a look on why but won't take too much time on this

**Review by sLorenzini — APPROVED** [review]
Hello,

As discussed with @NeOMakinG, we can merged this PR.

QA approved ✅ 

Thank you

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @sLorenzini

**Pull request merged**
