### PR TITLE
Add class for additional category description

### LINKED ISSUE #29383: ID for additional category description is missing
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Is your feature request related to a problem?

New additonal category description is missing ID

1. Category page
2. Find additonal description
3. Check for ID

### Describe the solution you'd like

ID existing

### Additional context

- PS version : 8.0.0 Beta1
- PHP version(s) : 7.4

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

### PR DESCRIPTION
**Pull request by JBWModules**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Specifc ID is missing
| Type?             |  improvement 
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes [29383](https://github.com/PrestaShop/PrestaShop/issues/29383)
| How to test?      | Open category page with addtional description
| Possible impacts? | n/a

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
Why not 🍬 

What's your use case of this ID?

**Comment by JBWModules** [comment]
> 

e.g. special CSS styling of this text

**Comment by SharakPL** [comment]
> > 
> 
> e.g. special CSS styling of this text

If just for styling then it should be class, not id.

**Comment by JBWModules** [comment]
I used ID as same is used in the normal category description.

**Comment by NeOMakinG** [comment]
> I used ID as same is used in the normal category description.

Yeah but this is an error we can't get rid of because of retro compatibility, I would agree with @SharakPL to use a class if you don't mind 🙏

**Review by yanmakouf — APPROVED** [review]
Nothing more to say :) +1 on @SharakPL comment

**Review by kpodemski — CHANGES_REQUESTED** [review]
Please change `id` to `class` as it was suggested by other reviewers 👍

**Comment by JBWModules** [comment]
Changed to class

**Review by kpodemski — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by NeOMakinG** [comment]
@PrestaShop/qa-team could be tested by a dev easily as it's just code context and not containing user-facing changes

**Comment by Robin-Fischer-PS** [comment]
Yep, can be tested by a dev, thanks for the ping @NeOMakinG and thanks for the PR @JBWModules !

**Comment by NeOMakinG** [comment]
Works as expected 👍 

Thanks @JBWModules

**Pull request merged**
