### PR TITLE
Avoid malformed ld+json if logo_details is missing

### LINKED ISSUE #28709: Generated microdata in head-jsonld.tpl is wrong if logo_details not available
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

if you have a condition at line 31 (that could be false) https://github.com/PrestaShop/classic-theme/blob/5632e4a90ce73ae529ceefbbf1f5f7eea0f755b4/templates/_partials/microdata/head-jsonld.tpl#L31

then you must take into account the resulting json, and that would be invalid if the condition is false because of the trailing comma, this patch simply puts the comma inside the condition so the resulting concatenation is well formed.

### Expected behavior

valid json if logo_detail missing

### Steps to reproduce

have logo_details missing

### PrestaShop version(s) where the bug happened

1.7.6.8

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by drc0**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | If  $shop.logo_details is missing then a malformed json was outputted given a trailing comma
| Type?             | bug fix
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/28709.
| BC breaks?        |  no
| Deprecations?     | no

### CODE REVIEW

**Review by matks — CHANGES_REQUESTED** [review]
Hello @drc0 the fix looks good but could you please submit a bug report with your scenario https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=Bug%2CNew&template=1_bug_report.yml ?

We can only validate your PR if we have a clear, reproducible scenario we can follow to observe the bug. In order to be able to explore your PR, to verify any side-effects, to make sure it is correct, we need a complete understanding of it, and so does the QA team. That's why a list of steps "1. do this 2. do then that 3. we should see ... but instead we should see ..." is a must-have needed for us to verify the bug 😉 . So before we review the PR we need the bug report confirmed.

Thank you

**Comment by NeOMakinG** [comment]
Makes sense, will approve when testing steps are updated

**Comment by drc0** [comment]
> Hello @drc0 the fix looks good but could you please submit a bug report with your scenario https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=Bug%2CNew&template=1_bug_report.yml ?
> 
> We can only validate your PR if we have a clear, reproducible scenario we can follow to observe the bug. In order to be able to explore your PR, to verify any side-effects, to make sure it is correct, we need a complete understanding of it, and so does the QA team. That's why a list of steps "1. do this 2. do then that 3. we should see ... but instead we should see ..." is a must-have needed for us to verify the bug wink . So before we review the PR we need the bug report confirmed.
> 
> Thank you

Hello @matks thanks for answering, I didn't thought an issue was necessary, sorry, anyway here it is
https://github.com/PrestaShop/PrestaShop/issues/28709

**Review by kpodemski — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Hello everyone,

The linked issue is `TBR` + `Waiting for Dev`, means not `Verified` yet.
So, I'm adding the label `Waiting for Dev` to this PR, cause the linked issue need to be `Verified`, and it will be better if a Dev test this PR.

Thanks!

**Review by FabienPapet — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @FabienPapet for testing and thank you @drc0 for the PR

**Pull request merged**
