### PR TITLE
fix simple table tag

### PR DESCRIPTION
**Pull request by drc0**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | tix table tag
| Type?             | bug fix
| BC breaks?        |  no
| Deprecations?     |  no
| Possible impacts? | Custom css on first table th that now is td

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Th in first cell is a legitimate syntax for bootstrap 4.6:

https://getbootstrap.com/docs/4.6/content/tables/

I will wait for @NeOMakinG to state his opinion.

**Comment by kpodemski** [comment]
> Th in first cell is a legitimate syntax for bootstrap 4.6:
> 
> 
> 
> https://getbootstrap.com/docs/4.6/content/tables/
> 
> 
> 
> I will wait for @NeOMakinG to state his opinion.

Good to know! 👍🏻

**Comment by Hlavtox** [comment]
Also: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th

**Comment by NeOMakinG** [comment]
It's a valid syntax yes.

@drc0 can you please give us more information on why you are trying to change this? I don't get it like that, without issues and description

If you feel like your contribution is relevant, create an issue and let's talk about it.

**Comment by drc0** [comment]
> It's a valid syntax yes.
> 
> @drc0 can you please give us more information on why you are trying to change this? I don't get it like that, without issues and description
> 
> If you feel like your contribution is relevant, create an issue and let's talk about it.

@NeOMakinG thanks for asking, the issue raised from a bug we had on our custom theme derived from classic-theme, we styled that table with a selector like tbody td, so it was a styling bug and not a semantic one. Your comments in this PR are valid though and having <th scope="row">[code]</th> has his validity. I'm not feeling changing this to td has his pros anymore, and I'm going to close this PR. 
thanks

**Pull request closed without merging**
