### PR TITLE
Fix: issue 37194

### LINKED ISSUE #37194: Missing/Incorrect CSS for div "carrier-extra-content" - hook "displayCarrierExtraContent"
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If any module add text to "carrier-extra-content" via hook "displayCarrierExtraContent", it's not stylled properly. Especially on mobile, it's broken. Check screenshot.
3 problems:
A) it's not aligned properly (because missing "margin: auto;" like for element "delivery-option")
B) unnecessary (not connected) dash to the right
C) it is not indented from the bottom, then it looks like part of the note.
Untitled

### Expected behavior

It must be aligned and working well. There is more options how to fix, but I am not front end developer.

Maybe @tblivet is a suitable candidate for fix (PR)? :)

### Steps to reproduce

1. open website https://demo.prestashop.com/#/en/front and click click click to order section "3" - shipping method
2. open JS konzole (F12)
3. fill there "$('.carrier-extra-content').text('Lorem ipsum dolor sit amet.');" and press enter
4. you will see results

You can make module for this purpose as well, but this is faster and easier.

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

https://www.openservis.cz/

### PR DESCRIPTION
**Pull request by tblivet**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fix issue https://github.com/PrestaShop/PrestaShop/issues/37194
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/37194
| Sponsor company   | @PrestaShopCorp
| How to test?      | Test is describe in the issue https://github.com/PrestaShop/PrestaShop/issues/37194

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hello @tblivet!

This is your first pull request on [classic-theme](https://github.com/PrestaShop/classic-theme/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

**Review by ga-devfront — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @tblivet ,

I tested with 8.2.x and 9.0.x, I don't have the expected behavior.

Before, the text was displayed (even if misaligned), but with the PR, the text is never displayed.

Before :


https://github.com/user-attachments/assets/fee02ada-b7a3-4cf1-873d-0c7e0954e3af



After :


https://github.com/user-attachments/assets/71846662-13e2-42b8-9f44-22d100aaf69f



Am I missing something ?
Thanks!

**Comment by tblivet** [comment]
Hello @florine2623 👋
After executing the code in the console, you can click on the other carrier to display the extra content, and it should work as expected.
However, the content added by the code in the console does not reflect the real behavior of this block. The content is tested directly in the code, and if the extra content is not empty, the block will be displayed by default.

**Review by florine2623 — APPROVED** [review]
Thanks @tblivet for the details.

I have retested it and it works as expected :

https://github.com/user-attachments/assets/55b9bebf-7d68-4e82-8571-809cddb73be5

It is QA ✅ !

**Comment by ps-jarvis** [comment]
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.

**Comment by ShaiMagal** [comment]
@tblivet thanks :)

**Pull request merged**
