### PR TITLE
Fix:30071 - Button of file field in customization product has a smaller height rather than its field

### LINKED ISSUE #30071: FO - Button of file field in customization product has a smaller height rather than its field
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In my customizable product, I have the file field to put an image. But the button "Choose file" has a smaller height rather than its field
Tested on 1.7.8.x/8.0.x branches and 1.7.7.8 version. No regression same bug on all versions

customization-button-not-aligned-button-view

- 1.7.7.8 ❌ 
1778-customization-button-not-aligned-product-view

- 1.7.8.x ❌ 
178x-customization-button-not-aligned-product-view

- 8.0.x ❌ 
80x-customization-button-not-aligned-product-view

### Expected behavior

"Choose file" button should have the same height than its field

### Steps to reproduce

1. Go to BO > Catalog > Products > Edit "Customizable mug" product
2. Go to "Options" tab in product page V1 or "Specifications" tab in product page v2 > Go to "Customization" section
3. Click on "Add a customization field" button > Write a label and choose the "File" type, no need to be required
4. Click on "Save" button > Click on "Preview" button
5. On the FO tab just opened, see error

### PrestaShop version(s) where the bug happened

8.0.x / 1.7.8.x / 1.7.7.8

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Arpit-Gulgulia**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fix for issue https://github.com/PrestaShop/PrestaShop/issues/30071
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/30071.
| How to test?      | Follow Issue reproduce steps.
| Possible impacts? | NA.

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
Might be the solution 🍬

**Comment by Arpit-Gulgulia** [comment]
Can we trigger the CI to make sure it doesn't break anything in the pipeline. Hopping to get it tested by QAs soon.

**Review by mflasquin — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @Arpit-Gulgulia,

I have tested your PR and it's OK for me. Thank you ! :tada: 

image

**Review by paulnoelcholot — APPROVED** [review]

**Comment by matks** [comment]
Thank you @Arpit-Gulgulia

**Pull request merged**
