### PR TITLE
GA : Build ZIP File and push it to release

### PR DESCRIPTION
**Pull request by Progi1984**
**This should go to 2.0.x, 2.1.x and develop.**

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | GA : Build ZIP File and push it to release
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| Sponsor company   | @PrestaShopCorp
| How to test?      | CI is :green_circle: and the ZIP for Classic is available : https://github.com/PrestaShop/classic-theme/actions/runs/4055277378 :tada:

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]
ZIP OK 🥳

**Comment by Progi1984** [comment]
Ping @PrestaShop/committers

**Review by nicosomb — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by Hlavtox** [comment]
Can I merge it? There is nothing more to test than checking the zip in CI. 🤷‍♂️

**Comment by Progi1984** [comment]
Ping @PrestaShop/qa-functional

**Comment by HanaRebaiQA** [comment]
Hello @Hlavtox 

It's Ok for us. GO

Thanks @Progi1984 for your PR

**Comment by nicosomb** [comment]
Thank you @Progi1984 and @HanaRebaiQA !

**Pull request merged**
