### PR TITLE
Add TikTok icon

### LINKED ISSUE #30229: Add TikTok to `ps_socialfollow` module
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Everything is in the title. TikTok is a must-have social network in 2022.

### Describe the solution you'd like

Add TikTok to `ps_socialfollow` module. I'll make a PR to add it.

### Alternatives you've considered

_No response_

### Additional context

_No response_

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

### PR DESCRIPTION
**Pull request by micka-fdz**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add TikTok icon for `ps_socialfollow` module.
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/30229.
| How to test?      | Should test with ps_socialfollow with TikTok filled
| Possible impacts? | -

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Review by lartist — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @micka-fdz,

Thanks for your PR. I tested it and the TikTok logo is too small and not centered on the button. It would have to be.
However, I have cleaned the cache of my browser and my BO.


Thanks you

image

**Comment by micka-fdz** [comment]
Hi @NeOMakinG,

Any idea about @paulnoelcholot issue? Maybe an issue with my SVG file.
Where do the other icon files come from?

**Comment by NeOMakinG** [comment]
> Hi @NeOMakinG,
> 
> Any idea about @paulnoelcholot issue? Maybe an issue with my SVG file. Where do the other icon files come from?

Probably an SVG problem yeah, open the others and check the diff!

Idk where they come from, this is a very old module :(

**Comment by leemyongpakvn** [comment]
@micka-fdz I see hummingbird uses `"material-design-icons-iconfont": "^6.7.0"` while classic uses `"material-design-icons-iconfont": "^5.0.1"`. Maybe upgrade this dependency can solve the problem.

**Pull request closed without merging**
