### PR TITLE
Add identifier when there are no results

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add identifier when there are no results
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | Relative to PrestaShop/PrestaShop#29683
| Possible impacts? | N/A

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
@Progi1984 I believe we could validate this PR by running the tests https://github.com/PrestaShop/PrestaShop/pull/29683 wdyt?

**Comment by Progi1984** [comment]
Affirmative, it's dependent. But I need this PR to be merged for merging the Core one.

**Review by sLorenzini — APPROVED** [review]
hello @Progi1984,

Thank you for this PR.
Tested on 8.0.x with PHP 7.3.

ID is well added on "No search" page in FO:

id-no-search

The search is correctly working

QA approved ✅ 

Thanks

**Comment by Hlavtox** [comment]
Thank you @Progi1984 for your work! :-)

**Pull request merged**
