### PR TITLE
Update version in theme.yml

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Update version in theme.yml
| Type?             |improvement 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     |
| Sponsor company   |
| How to test?      | CI 🟢

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]
Thanks @lartist

**Review by nicosomb — COMMENTED** [review]
This release won't be compatible with PS 8.0.x?

**Comment by lartist** [comment]
> This release won't be compatible with PS 8.0.x?

No 2.1.x is made for 8.1.x and 2.0.x is made for 8.0.x.

**Review by nicosomb — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @lartist ,

No need QA for this PR ! Thanks !

**Pull request merged**
